const WHATSAPP_NUMBER = "5511970321742";
const GMAIL_ADDRESS = "contacto@belingolife.com";
const INSTAGRAM_URL = "https://www.instagram.com/belingolife/";
const STORAGE_KEY = "belingolife-language";
const DEFAULT_LANGUAGE = "pt-BR";

const translations = {
  "pt-BR": {
    navLevels:"Níveis", navMethod:"Métodos", navFeedback:"Feedbacks", navContact:"Contato",
    heroMicro:"aulas online", heroSub:"with teacher Isa.", heroCta:"Agendar aula experimental",
    aboutBold:"Eu estudo idiomas já por 10 anos e o Inglês é um deles!", aboutText:"Minhas séries favoritas são Friends, The Office e Brooklyn 99. Elas me ajudaram muuuuito a aprender o Inglês de forma natural! Eu uso muito essas séries durante as aulas.",
    beliefOne:"A fluência é um <strong>processo</strong>, não um destino!", beliefTwo:"Todos os idiomas são complexos, extensos e envolvem muito mais do que apenas palavras.", beliefThree:"Aprender um idioma é um processo contínuo. Nosso objetivo é conseguir nos <strong>comunicar</strong> de forma confortável e <strong>natural!</strong>",
    courseOne:"As aulas são realizadas pelo Google Meet e têm duração de 1 hora.", courseTwo:"Como material, usaremos os livros da série <strong>American English File</strong>. Eu disponibilizo o material, então você não necessariamente precisa comprar a versão física.", courseThree:"Os assuntos são adaptados para a sua necessidade e objetivo!", courseFour:"Por enquanto não há emissão de certificado.", courseSide:"Nas aulas para crianças/adolescentes, usaremos materiais adaptados por idade e objetivo.",
    levelsTitle:"Níveis", methodPanelTitle:"Métodos", methodOneTitle:"Active recall", methodOneText:"Resgatar informações da memória antes de consultar o material.", methodTwoTitle:"Spaced repetition", methodTwoText:"Revisões inteligentes em intervalos para fixar vocabulário.", methodThreeTitle:"Input natural", methodThreeText:"Séries, vídeos e situações reais para aprender com contexto.",
    feedbackOpen:"Ver feedbacks", feedbackTitle:"Feedbacks reais", feedbackOne:" ", feedbackTwo:"Mensagens, evolução e carinho dos alunos.", feedbackThree:"Aulas com material, organização e prática.",
    availabilityTitle:"Horários disponíveis:", availabilityText:"Consulte os horários atuais pelo WhatsApp.", investmentTitle:"Investimento:", investmentText:"Planos e disponibilidade sob consulta.", contactTitle:"Contato", contactText:"Vamos agendar uma aula experimental, sem custo?", workQuestion:"Vamos agendar uma aula experimental, sem custo?",
    whatsappDefault:"Olá! Quero agendar uma aula experimental sem custo com a teacher Isa.", mailSubject:"Consulta sobre aulas de inglês", mailBody:"Olá! Quero saber mais sobre as aulas de inglês.",
    levels:{beginner:{label:"Iniciante",title:"Base para começar a falar",description:"Frases essenciais, pronúncia e estrutura para conversas simples.",example:"“My name is Ana. I like coffee.”"}, intermediate:{label:"Intermediário",title:"Conversas com mais confiança",description:"Vocabulário prático, tempos verbais e situações do dia a dia.",example:"“I’ve been studying English for two years.”"}, advanced:{label:"Avançado",title:"Fluência para objetivos reais",description:"Discussões, trabalho, estudos internacionais e correção de detalhes.",example:"“I’d rather focus on speaking naturally.”"}}
  },
  "es-ES": {navLevels:"Niveles",navMethod:"Métodos",navFeedback:"Feedbacks",navContact:"Contacto",heroMicro:"clases online",heroSub:"with teacher Isa.",heroCta:"Agendar clase experimental",aboutBold:"Estudio idiomas desde hace 10 años y el inglés es uno de ellos!",aboutText:"Mis series favoritas son Friends, The Office y Brooklyn 99. Me ayudaron muchísimo a aprender inglés de forma natural y las uso mucho en clase.",beliefOne:"La fluidez es un <strong>proceso</strong>, no un destino!",beliefTwo:"Todos los idiomas son complejos, extensos y son mucho más que palabras.",beliefThree:"Aprender un idioma es un proceso continuo. El objetivo es <strong>comunicarnos</strong> de forma cómoda y <strong>natural!</strong>",courseOne:"Las clases son por Google Meet y duran 1 hora.",courseTwo:"Usaremos libros de la serie <strong>American English File</strong>. El material será proporcionado.",courseThree:"Los temas se adaptan a tu necesidad y objetivo!",courseFour:"Por ahora no se emite certificado.",courseSide:"Para niños/adolescentes usamos materiales adaptados por edad y objetivo.",levelsTitle:"Niveles",methodPanelTitle:"Métodos",methodOneTitle:"Active recall",methodOneText:"Recordar información antes de mirar el material.",methodTwoTitle:"Spaced repetition",methodTwoText:"Repasos en intervalos para fijar vocabulario.",methodThreeTitle:"Input natural",methodThreeText:"Series, videos y situaciones reales para aprender con contexto.",feedbackOpen:"Ver feedbacks",feedbackTitle:"Feedbacks reales",feedbackOne:"“Teacher, tus clases son maravillosas...”",feedbackTwo:"Mensajes, evolución y cariño de los alumnos.",feedbackThree:"Clases con material, organización y práctica.",availabilityTitle:"Horarios disponibles:",availabilityText:"Consulta horarios actuales por WhatsApp.",investmentTitle:"Inversión:",investmentText:"Planes y disponibilidad a consultar.",contactTitle:"Contacto",contactText:"¿Agendamos una clase experimental sin costo?",workQuestion:"¿Agendamos una clase experimental sin costo?",whatsappDefault:"Hola! Quiero agendar una clase experimental sin costo con teacher Isa.",mailSubject:"Consulta sobre clases de inglés",mailBody:"Hola! Quiero saber más sobre las clases de inglés.",levels:{beginner:{label:"Principiante",title:"Base para empezar a hablar",description:"Frases esenciales, pronunciación y estructura para conversaciones simples.",example:"“My name is Ana. I like coffee.”"},intermediate:{label:"Intermedio",title:"Conversaciones con más confianza",description:"Vocabulario práctico, tiempos verbales y situaciones cotidianas.",example:"“I’ve been studying English for two years.”"},advanced:{label:"Avanzado",title:"Fluidez para objetivos reales",description:"Debates, trabajo, estudios internacionales y corrección de detalles.",example:"“I’d rather focus on speaking naturally.”"}}},
  "fr-FR": {}, "ko-KR": {}, "zh-CN": {}, "ja-JP": {}
};
["fr-FR","ko-KR","zh-CN","ja-JP"].forEach(lang=>{translations[lang]={...translations["pt-BR"], navLevels: lang==="fr-FR"?"Niveaux":"Levels", navMethod: lang==="fr-FR"?"Méthodes":"Methods", navContact: lang==="fr-FR"?"Contact":"Contact"};});
const shorts={"pt-BR":"PT","es-ES":"ES","fr-FR":"FR","ko-KR":"KO","zh-CN":"ZH","ja-JP":"JA"};
let currentLang=localStorage.getItem(STORAGE_KEY)||DEFAULT_LANGUAGE;
function t(){return translations[currentLang]||translations[DEFAULT_LANGUAGE];}
function applyLanguage(lang){currentLang=lang;localStorage.setItem(STORAGE_KEY,lang);document.documentElement.lang=lang;document.getElementById("current-language").textContent=shorts[lang]||"PT";document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(t()[key]) el.innerHTML=t()[key];});document.querySelectorAll("#language-menu button").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));updateLevel(document.querySelector(".tab.active")?.dataset.level||"beginner");updateLinks();}
function updateLinks(){const msg=encodeURIComponent(t().whatsappDefault);const wa=`https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`;["hero-whatsapp","contact-whatsapp-link","whatsapp-float","work-whatsapp"].forEach(id=>{const el=document.getElementById(id);if(el)el.href=wa;});document.querySelectorAll("[data-instagram-link],#contact-instagram-link").forEach(el=>el.href=INSTAGRAM_URL);const mail=`mailto:${GMAIL_ADDRESS}?subject=${encodeURIComponent(t().mailSubject)}&body=${encodeURIComponent(t().mailBody)}`;const gmail=document.getElementById("gmail-link");if(gmail)gmail.href=mail;}
function togglePanel(id){const panel=document.getElementById(id);if(!panel)return;const isOpen=panel.classList.toggle("is-open");panel.setAttribute("aria-hidden",String(!isOpen));document.querySelectorAll(`[data-target="${id}"]`).forEach(btn=>{btn.classList.toggle("is-active",isOpen);btn.setAttribute("aria-expanded",String(isOpen));});if(isOpen)setTimeout(()=>panel.scrollIntoView({behavior:"smooth",block:"start"}),80);}
function updateLevel(level){const data=t().levels[level]||t().levels.beginner;document.getElementById("level-tag").textContent=data.label;document.getElementById("course-title").textContent=data.title;document.getElementById("course-description").textContent=data.description;document.getElementById("level-example").textContent=data.example;}
document.addEventListener("DOMContentLoaded",()=>{const menu=document.getElementById("language-menu");document.getElementById("language-toggle").addEventListener("click",e=>{e.stopPropagation();menu.classList.toggle("open");});menu.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{menu.classList.remove("open");applyLanguage(btn.dataset.lang);}));document.addEventListener("click",()=>menu.classList.remove("open"));document.querySelectorAll(".panel-toggle").forEach(btn=>btn.addEventListener("click",()=>togglePanel(btn.dataset.target)));document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");updateLevel(btn.dataset.level);}));applyLanguage(currentLang);});
